#[Info]
site_name: My Notebook
site_url: https://song-hz.github.io/myblog/test/
site_author: song-hz

 
# [Navigtion]
nav: 
  - 博客:
    - 好用/好玩网站分享: index.md
  - 开发: 
    - Markdown: test.md
  - 闲话:
    - 原神: error.md
    - 诗文:
      - 滕王阁序: test.md
        - 滕王阁序: test.md
          - 滕王阁序: test.md
            - 滕王阁序: test.md
          



  
copyright: Copyright &copy; song-hz # 左下角的版权声明
  
 
 
 