#[Info]
site_name: My Notebook

# [Navigtion]
nav: 
  - Home: index.md
  - 代码错误:
    - 通用错误: code/error.md
  - 代码学习:
    - tensorflow: framework/tensorflow.md
  - 有关环境:
    - Anaconda环境: environment/Anaconda.md
  
copyright: Copyright &copy; song-hz # 左下角的版权声明
  
 
 
 