#[Info]
site_name: My Notebook

# [Navigtion]
nav: 
  - 环境配置: environment/overview.md
  - 代码: code/overview.md
  - 深度学习: framework/overview.md
  - 我的项目: myproject/overview.md
  - 课程学习: mystudy/overview.md
  
copyright: Copyright &copy; song-hz # 左下角的版权声明
  
 
 
 